/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author Usuario
 */
public class Menu_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Admin
     */
    public Menu_Admin() {
        initComponents();
         this.setLocationRelativeTo(null);
         this.setResizable(false);
             this.setTitle("ArriendosTemporada - Desktop App");
          setIconImage(new ImageIcon(getClass().getResource("/iconos/icono - agricultura.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDialog1 = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Admin_cerrarsesion = new javax.swing.JButton();
        RG_C_Externo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PU_venta_externa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        contratobtn = new javax.swing.JButton();
        vercliente = new javax.swing.JButton();
        elicliente = new javax.swing.JButton();
        veredi = new javax.swing.JButton();
        eliedi = new javax.swing.JButton();
        actualizarcliente = new javax.swing.JButton();
        actualizaredificios = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        vercontrato = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Menu Administrador");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono - administrador.png"))); // NOI18N

        Admin_cerrarsesion.setBackground(new java.awt.Color(0, 51, 153));
        Admin_cerrarsesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Admin_cerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        Admin_cerrarsesion.setText("Cerrar sesion");
        Admin_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_cerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Admin_cerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(71, 71, 71)
                .addComponent(Admin_cerrarsesion)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        RG_C_Externo.setBackground(new java.awt.Color(255, 255, 255));
        RG_C_Externo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RG_C_Externo.setForeground(new java.awt.Color(0, 51, 153));
        RG_C_Externo.setText("Registrar");
        RG_C_Externo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RG_C_ExternoActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono - usuario.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edificios");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icono - agricultura.png"))); // NOI18N

        PU_venta_externa.setBackground(new java.awt.Color(255, 255, 255));
        PU_venta_externa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PU_venta_externa.setForeground(new java.awt.Color(0, 51, 153));
        PU_venta_externa.setText("Registrar");
        PU_venta_externa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PU_venta_externaActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(170, 4, 254));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Clientes");

        contratobtn.setBackground(new java.awt.Color(255, 255, 255));
        contratobtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        contratobtn.setForeground(new java.awt.Color(0, 51, 153));
        contratobtn.setText("Ingresar contrato");
        contratobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratobtnActionPerformed(evt);
            }
        });

        vercliente.setBackground(new java.awt.Color(255, 255, 255));
        vercliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vercliente.setForeground(new java.awt.Color(0, 51, 153));
        vercliente.setText("Visualizar");
        vercliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verclienteActionPerformed(evt);
            }
        });

        elicliente.setBackground(new java.awt.Color(255, 255, 255));
        elicliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        elicliente.setForeground(new java.awt.Color(0, 51, 153));
        elicliente.setText("Eliminar");
        elicliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliclienteActionPerformed(evt);
            }
        });

        veredi.setBackground(new java.awt.Color(255, 255, 255));
        veredi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        veredi.setForeground(new java.awt.Color(0, 51, 153));
        veredi.setText("Visualizar");
        veredi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verediActionPerformed(evt);
            }
        });

        eliedi.setBackground(new java.awt.Color(255, 255, 255));
        eliedi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eliedi.setForeground(new java.awt.Color(0, 51, 153));
        eliedi.setText("Eliminar");
        eliedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliediActionPerformed(evt);
            }
        });

        actualizarcliente.setBackground(new java.awt.Color(255, 255, 255));
        actualizarcliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        actualizarcliente.setForeground(new java.awt.Color(0, 51, 153));
        actualizarcliente.setText("Actualizar");
        actualizarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarclienteActionPerformed(evt);
            }
        });

        actualizaredificios.setBackground(new java.awt.Color(255, 255, 255));
        actualizaredificios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        actualizaredificios.setForeground(new java.awt.Color(0, 51, 153));
        actualizaredificios.setText("Actualizar");
        actualizaredificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaredificiosActionPerformed(evt);
            }
        });

        imprimir.setBackground(new java.awt.Color(255, 255, 255));
        imprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        imprimir.setForeground(new java.awt.Color(0, 51, 153));
        imprimir.setText("Imprimir Contrato");
        imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirActionPerformed(evt);
            }
        });

        vercontrato.setBackground(new java.awt.Color(255, 255, 255));
        vercontrato.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vercontrato.setForeground(new java.awt.Color(0, 51, 153));
        vercontrato.setText("Ver contratos");
        vercontrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vercontratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(132, 154, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(92, 92, 92))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 182, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(126, 126, 126))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vercliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RG_C_Externo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(elicliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actualizarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(veredi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliedi, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PU_venta_externa, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizaredificios, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contratobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vercontrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(211, 211, 211))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RG_C_Externo)
                    .addComponent(PU_venta_externa))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vercliente)
                    .addComponent(veredi))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarcliente)
                    .addComponent(actualizaredificios))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elicliente)
                    .addComponent(eliedi))
                .addGap(44, 44, 44)
                .addComponent(contratobtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vercontrato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imprimir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratobtnActionPerformed
        this.setVisible(false);
        Administrador_Ingresar_Contrato AICO = new Administrador_Ingresar_Contrato();
        AICO.setVisible(true);
    }//GEN-LAST:event_contratobtnActionPerformed

    private void PU_venta_externaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PU_venta_externaActionPerformed

        this.setVisible(false);
        Edificio_Registrar APV = new Edificio_Registrar();
        APV.setVisible(true);

    }//GEN-LAST:event_PU_venta_externaActionPerformed

    private void RG_C_ExternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RG_C_ExternoActionPerformed
        this.setVisible(false);
        Admin_Registro_CX RCX = new Admin_Registro_CX();
        RCX.setVisible(true);
    }//GEN-LAST:event_RG_C_ExternoActionPerformed

    private void Admin_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_cerrarsesionActionPerformed

        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);

    }//GEN-LAST:event_Admin_cerrarsesionActionPerformed

    private void verclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verclienteActionPerformed
        this.setVisible(false);
        Ver_Cliente VC = new Ver_Cliente();
        VC.setVisible(true);
    }//GEN-LAST:event_verclienteActionPerformed

    private void eliclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliclienteActionPerformed
        this.setVisible(false);
        Borrar_cliente borrarC= new Borrar_cliente();
        borrarC.setVisible(true);
    }//GEN-LAST:event_eliclienteActionPerformed

    private void verediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verediActionPerformed
        this.setVisible(false);
        Departamentos APV = new Departamentos();
        APV.setVisible(true);
    }//GEN-LAST:event_verediActionPerformed

    private void eliediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliediActionPerformed
       this.setVisible(false);
        DepartamentosBorrar borrar = new DepartamentosBorrar();
        borrar.setVisible(true);
    }//GEN-LAST:event_eliediActionPerformed

    private void actualizarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarclienteActionPerformed
        this.setVisible(false);
        Actualizar_cliente actua = new Actualizar_cliente();
        actua.setVisible(true);
    }//GEN-LAST:event_actualizarclienteActionPerformed

    private void actualizaredificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaredificiosActionPerformed
        this.setVisible(false);
        Edificio_Actualizar eact = new Edificio_Actualizar();
        eact.setVisible(true);
    }//GEN-LAST:event_actualizaredificiosActionPerformed

    private void imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirActionPerformed
        this.setVisible(false);
        contrato_imprimir conimp = new contrato_imprimir();
        conimp.setVisible(true);
    }//GEN-LAST:event_imprimirActionPerformed

    private void vercontratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vercontratoActionPerformed
        this.setVisible(false);
        contrato_ver vercon = new contrato_ver();
        vercon.setVisible(true);
    }//GEN-LAST:event_vercontratoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_cerrarsesion;
    private javax.swing.JButton PU_venta_externa;
    private javax.swing.JButton RG_C_Externo;
    private javax.swing.JButton actualizarcliente;
    private javax.swing.JButton actualizaredificios;
    private javax.swing.JButton contratobtn;
    private javax.swing.JButton elicliente;
    private javax.swing.JButton eliedi;
    private javax.swing.JButton imprimir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton vercliente;
    private javax.swing.JButton vercontrato;
    private javax.swing.JButton veredi;
    // End of variables declaration//GEN-END:variables
}
